name: PlatformIO Run

on: [pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: karniv00l/platformio-run-action@0.1.0
